import {
  Utensils,
  Coffee,
  ShoppingCart,
  ShoppingBag,
  Car,
  Bus,
  Bike,
  Fuel,
  Home as HomeIcon,
  Building2,
  Lightbulb,
  Droplet,
  Wifi,
  Smartphone,
  Laptop,
  Tv,
  Music,
  Film,
  Gamepad2,
  Dumbbell,
  HeartPulse,
  Stethoscope,
  Pill,
  GraduationCap,
  BookOpen,
  Briefcase,
  Banknote,
  TrendingUp,
  PiggyBank,
  Gift,
  PartyPopper,
  Plane,
  Hotel,
  MapPin,
  Shirt,
  Scissors,
  Dog,
  Cat,
  PawPrint,
  Baby,
  Users,
  Heart,
  ShieldCheck,
  Wrench,
  Tag,
  MoreHorizontal,
  Sparkles,
  Trophy,
  Pizza,
  Wine,
  Beer,
  Receipt,
  CreditCard,
  Camera,
  Palette,
  Truck,
  ArrowRightLeft,
  Bone,
  Cake,
  IceCreamCone,
  Salad,
  Drama,
  BedDouble,
  Sofa,
  Hammer,
  Glasses,
  Watch,
  Gem,
  Flower2,
  TreePalm,
  Umbrella,
  type LucideIcon,
} from "lucide-react";

/**
 * Registro de íconos disponibles para categorías. La clave es exactamente
 * el string que se guarda en `Categoria.icono`; el valor es el componente
 * de lucide-react a renderizar. Para agregar más íconos a futuro, éste es
 * el único lugar que hay que tocar.
 */
export const ICONOS_CATEGORIA: Record<string, LucideIcon> = {
  Utensils,
  Coffee,
  ShoppingCart,
  ShoppingBag,
  Car,
  Bus,
  Bike,
  Fuel,
  Home: HomeIcon,
  Building2,
  Lightbulb,
  Droplet,
  Wifi,
  Smartphone,
  Laptop,
  Tv,
  Music,
  Film,
  Gamepad2,
  Dumbbell,
  HeartPulse,
  Stethoscope,
  Pill,
  GraduationCap,
  BookOpen,
  Briefcase,
  Banknote,
  TrendingUp,
  PiggyBank,
  Gift,
  PartyPopper,
  Plane,
  Hotel,
  MapPin,
  Shirt,
  Scissors,
  Dog,
  Cat,
  PawPrint,
  Baby,
  Users,
  Heart,
  ShieldCheck,
  Wrench,
  Tag,
  MoreHorizontal,
  Sparkles,
  Trophy,
  Pizza,
  Wine,
  Beer,
  Receipt,
  CreditCard,
  Camera,
  Palette,
  Truck,
  ArrowRightLeft,
  Bone,
  Cake,
  IceCreamCone,
  Salad,
  Drama,
  BedDouble,
  Sofa,
  Hammer,
  Glasses,
  Watch,
  Gem,
  Flower2,
  TreePalm,
  Umbrella,
};

const ICONO_POR_DEFECTO: LucideIcon = Tag;

/** Íconos que el usuario puede elegir al crear/editar una categoría (se excluye ArrowRightLeft: reservado para Transferencia). */
export const ICONOS_DISPONIBLES: string[] = Object.keys(ICONOS_CATEGORIA).filter(
  (nombre) => nombre !== "ArrowRightLeft"
);

/** Devuelve el componente de ícono para un nombre guardado; si no existe (dato viejo o corrupto), devuelve un ícono genérico en vez de romper la UI. */
export function obtenerIconoCategoria(nombreIcono: string): LucideIcon {
  return ICONOS_CATEGORIA[nombreIcono] ?? ICONO_POR_DEFECTO;
}
